### ISSUE TITLE
Multiple arguments

### ISSUE THREAD

**Issue by gdalle** [rafaqz/Interfaces.jl#14]
How do we include methods in the interface that take several arguments of different types?

**Comment by rafaqz** [comment]
Yeah, you would need to define an interface that is specifically for e.g. type a working where type b is the second argument to function f.

It would be cool if you could specify the traits allowed for b.

**Comment by gdalle** [comment]
At the moment I don't care about traits, but I would like to specify an interface like the following (let's ignore the liberties I took with Interfaces.jl syntax):

```
# Define the interface conditions
@interface AbstractGraph{V} (
    mandatory = (
        vertices(::AbstractGraph),
        edges(::AbstractGraph),
        neighbors(:::AbstractGraph{V}, ::V)
    ),
)
```

**Comment by gdalle** [comment]
See https://github.com/JuliaGraphs/GraphsBase.jl/issues/2

**Comment by rafaqz** [comment]
We jusr need to write the macro code to detect that I guess.

But do you only want to know that the methods exist? Or actually compile/run something?

If the second argument accepts `Any` we wont have proven much.

**Comment by gdalle** [comment]
If the goal is to have compile-time checking, we are not allowed to run anything, right?

**Comment by rafaqz** [comment]
The goal is not compile-time checking, thats a pretty limited check of an interface working. E.g. it cant catch half of the OffsetArrays.jl bugs and most other correctness bugs that got me thinking about this in the first place.

While the traits are compile time, the check can go in precompile or tests. 

So the fact that it actually runs is socially enforced rather than compiler enforced. Not perfect of course.

**Comment by gdalle** [comment]
The trouble is, for some of these functions there is no "default value" to run them on. Typically, the graphs interface _requires_ access functions but no specific constructors

**Comment by rafaqz** [comment]
You need to provide test objects to run the interface tests.

Or do you mean for the second argument? You could create thay from `oneunit(V)` in your example

**Comment by gdalle** [comment]
Riiight, so `Interfaces.implements` is a compile-time trait but it is only based on user declaration, and `Interfaces.test` is what a user should actually do before declaring that the interface is supported.

**Comment by gdalle** [comment]
So what needs to change is the syntax for interface declaration and testing.
I guess for testing, inside of a list of objects, one could have a list of named tuples or dictionaries?

**Comment by gdalle** [comment]
As for the macro, my first example might be a little hard to achieve in terms of parsing, but this simplified version would already go a long way:

```julia
@interface AbstractGraphInterface (
    mandatory = (
        vertices(g::AbstractGraph),
        edges(g::AbstractGraph),
        neighbors(g:::AbstractGraph, v)
    ),
)
```

Note the difference between the interface name and the type name, cause this is an inheritance-free interface unlike RequiredInterfaces.jl.

Then we could pass something like

```julia
Dict(g => MyConcreteGraph(), v => 1)
```

to the tests?

**Comment by rafaqz** [comment]
Can we separate out the nice syntax idea and multiple arguments idea? Ultimately the macro needs to generate some anonymous function anyway.

**Comment by rafaqz** [comment]
The output of the `@interface` macro has to end up being mandatory and optional NameTuples with values of `Union{Function,Tuple{Function}}` where the keys are the trait names.

Those functions get run in the tests for the each trait.

So working out the sytax of the final functions is the important part... thrn we can look at how to map that to a dsl like your example, if its actually necessary.

**Comment by gdalle** [comment]
I'm sorry I still don't understand what kind of "macro-free example" you want.
If I try to adhere to the Interfaces.jl syntax, I guess a minimal example would look like this:

```julia
@interface AbstractGraphInterface (
    mandatory = (
        has_vertex = (g, u) -> has_vertex(g, u) isa Bool,
        has_edge = (g, u, v) -> has_edge(g, u, v) isa Bool,
    ),
    optional = (;)
)
```

The main question I have is how to impose the type of `g` since it is not named anywhere in the interface definition.
And ideally, I would also like to make the types of `u` and `v` depend on `g`.

**Comment by rafaqz** [comment]
Thanks thats what I meant. 

If the object is an array or similar we can use `u = zero(eltype(g))` in the anonymous function and drop it from the arguments? 

I guess there are cases where things like that are not possible and we need a way to pass in the extra arguments to the tests on a trait-by-trait basis.

Isnt imposing types on g just `g -> g isa SomeType` ?

**Comment by gdalle** [comment]
> If the object is an array or similar we can use u = zero(eltype(g)) in the anonymous function and drop it from the arguments?

That's rather specific, and in our case it wouldn't work cause we want to apply this to arbitrary graphs created by the user, with arbitrary vertex types

> Isnt imposing types on g just g -> g isa SomeType ?

In my mind, the interface is linked to a single type, like `Duck`, or in my case a subtype `G <: AbstractGraph{V}`, where `V` is the vertex type. So I wanna specifw somehow that the `g` arguments are those of the type constrained by the interface

**Comment by rafaqz** [comment]
> That's rather specific

Well I did mention the general solution below that...


> So I wanna specify somehow that the g arguments are those of the type G constrained by the interface


All `g` in these examples are the same objects so `g -> g isa SomeType` is doing exactly what you want already?

**Comment by gdalle** [comment]
> All g in these examples are the same objects so g -> g isa SomeType is doing exactly what you want already?

Yes but where is the `SomeType` coming from? Does it become an additional argument to the interface?

```julia
@interface AbstractGraphInterface SomeType (
    mandatory = (
        has_vertex = (g::SomeType, u) -> has_vertex(g, u) isa Bool,
        has_edge = (g::SomeType, u, v) -> has_edge(g, u, v) isa Bool,
    ),
    optional = (;)
)
```
But in that case the anonymous functions cannot work until the user gives their actual `SomeType`, in our interface definition it can only be a mute variable

**Comment by rafaqz** [comment]
Im so confused... the person that implements the interface just writes the trait out like this or whatever:

```julia
istherighttype = g -> g isa SomeType
```

We can of course add this yo the macro as magic, but lets stick to functions here.

Or... are you trying to say you want a check that tgere are functions defined for exactly some specific type rather than a generic falback?

Otherwise Im lost here

**Comment by gdalle** [comment]
I think it might be a good idea to have a 15-min zoom call one of these days, if you're open to it 😅 this is getting a bit tedious

**Comment by rafaqz** [comment]
Its basically always like this lol... the difficulty of these discussions is a lot of why I stopped working on this package, I never experienced anything like it. 

Peoples idea of what an interface declaration is/should be is just wildly different.

But Im actually mostly free today, central european time zone.

**Comment by gdalle** [comment]
**Roadmap**

- Define an `Arguments` type wrapping a `NamedTuple` (see [Extents.jl](https://github.com/rafaqz/Extents.jl)
- Define a function `get_interface_type(a::Arguments)` returning the first type of the named tuple
- Transform any checks in `src/test.jl` to allow the vector of objects to be either `Duck` or `Argument{(Duck, ...)}`
- Add new tests for multi-argument functions `a -> f(a.x, a.y)`
- Explain that the first interface test should validate the `Argument`
- Add docs
