### ISSUE TITLE
What does `@implements dev ...` really do?

### ISSUE THREAD

**Issue by gdalle** [rafaqz/Interfaces.jl#18]
The docstring says it displays verbose tests, but one can run the tests before having declared that our type `@implements` the interface. In fact it may be wiser to do so.
Besides, I don't see where the `show` kwarg is used in the code

**Comment by rafaqz** [comment]
The docs are from the first implementation and probably contain things that dont make sense anymore.

Originally tests were run in precompilation automatically.

**Comment by rafaqz** [comment]
Deleteed
