### ISSUE TITLE
Include the required supertype in interface declarations

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/Interfaces.jl#26]
I'm thinking it may make sense if interface declarations have to include the required supertype, like:

```julia
@interface SomeInterface SomeType conditions docs
```

For interfaces without supertypes, like iteration, this would be `Any`

```julia
@interface IterationInterface Any conditions docs
```

Originally this was not included because the `Any` case is redundant. But now I think it might be nicely self documenting -
wherever there is `Any` its a trait only interface.

@gdalle any thoughts?

**Comment by gdalle** [comment]
I like that idea! And it's probably a minor code change
