### ISSUE TITLE
Graphs interface

### ISSUE THREAD

**Issue by gdalle** [rafaqz/Interfaces.jl#38]
My intern @olegfafurin and I are trying to formalize the [`AbstractGraph` interface](https://juliagraphs.org/Graphs.jl/dev/ecosystem/interface/) in this repo: https://github.com/gdalle/GraphsInterfaceChecker.jl

We might poke around and find missing stuff in Interfaces.jl

**Comment by rafaqz** [comment]
Cool.l! @olegfafurin please feel free to make issues here for literally any problems you have or missing features you find. That kind of feedback is really useful at this stage.

Note that #37 will change testing and implementation definition a little and #34 will allow (multiple) inheritance soon.

**Comment by gdalle** [comment]
The interface is more or less complete for the time being, and the tests have grown larger, in case you're interested to see your package in action @rafaqz

**Comment by rafaqz** [comment]
The tests look good! Happy its useful :)

**Comment by rafaqz** [comment]
Also nice use of readme as the interface description!

Do you imagine packages will have this as a dependency, or just for checking the interface?

**Comment by gdalle** [comment]
For now it's a prototype, still waiting to evolve. Ideally I'd put this in Graphs.jl, but I fear there might be some pushback.

**Comment by rafaqz** [comment]
Yes abosolutely. Packages could have it as a test dependency.
