### ISSUE TITLE
Links for documentation return error 404

### ISSUE THREAD

**Issue by Azzaare** [rafaqz/Interfaces.jl#4]
It seems the GitHub pages configuration for the documentation is not working (yet).

Based on the gh-pages branch content, I would assume it is related to the settings of the repository. I might be totally wrong though!

The package seems really nice, thank you!

**Comment by rafaqz** [comment]
Thanks, I probably just need to fix the documenter keys

**Comment by gdalle** [comment]
Up @rafaqz ? This would be cool to work together on the package

**Comment by gdalle** [comment]
@rafaqz links on the readme still don't work for me

**Comment by rafaqz** [comment]
We need to push something to trigger a docs build - there is nothing to link to

**Comment by rafaqz** [comment]
Hmm actually no there is... why is it not linking?

**Comment by gdalle** [comment]
idk what you just did but it works now

**Comment by rafaqz** [comment]
Somehow pages settings were messed up, no idea how that happened.

**Comment by gdalle** [comment]
I think we can close this
