### ISSUE TITLE
Register BaseInterfaces.jl?

### ISSUE THREAD

**Issue by MilesCranmer** [rafaqz/Interfaces.jl#48]
I thought BaseInterfaces.ArrayInterface looked pretty useful and wanted to add it to my test suite for DynamicQuantities for testing `QuantityArray`. However it looks like it's unregistered at the moment. Is this something on the roadmap or is BaseInterfaces intended only as an example?

**Comment by rafaqz** [comment]
It's meant to be registered, I just haven't had time to finish it (PhD + too many other packages...). Im not sure when I will have time either, definitely not in the next 4 months.

But if you have time to polish it up a bit and double check it all makes sense I can make time to review.

**Comment by MilesCranmer** [comment]
No rush! For me https://github.com/rafaqz/Interfaces.jl/pull/47 is much more important/timely, having BaseFeatures would just be gravy on top.

**Comment by rafaqz** [comment]
BaseInterfaces.jl is now registered :)
